"""SEO Agent for ContentOS.

Responsible for analyzing scripts and topics to generate search-optimized titles, descriptions, and tags.
"""

import os
import pathlib
from typing import Optional
from pydantic import BaseModel, Field
from google.adk.agents import Agent
from google.adk.models import Gemini
from google.adk.skills import load_skill_from_dir
from google.adk.runners import Runner
from google.adk.sessions.in_memory_session_service import InMemorySessionService
from google.genai import types

# Load the seo-optimizer skill
SKILL_DIR = pathlib.Path(__file__).parent.parent / "skills" / "seo-optimizer"
skill = load_skill_from_dir(SKILL_DIR)

class SeoOutput(BaseModel):
    """Structured SEO metadata package output format."""
    titles: list[str] = Field(description="Three title options. Each must be under 60 characters.")
    description: str = Field(description="YouTube video description, 150-200 words, integrating keywords naturally.")
    tags: list[str] = Field(description="10-15 tags, mixture of broad, specific, and long-tail tags.")
    thumbnail_brief: str = Field(description="Visual brief/instructions for a thumbnail designer.")
    chapter_markers: list[str] = Field(description="Timestamp markers based on script segments (e.g., '0:00 - Hook').")

# Define the SEO Agent
seo_agent = Agent(
    name="SEOAgent",
    model=Gemini(model="gemini-2.5-flash"),
    instruction=(
        f"{skill.instructions}\n\n"
        "Your task is to accept the video topic and script draft as input, and generate a complete YouTube SEO package.\n"
        "All outputs must strictly adhere to the RennAsks tone and style constraints:\n"
        "- Strict lowercase preference for titles\n"
        "- Under 60 characters per title\n"
        "- Description must be 150-200 words, distributing keywords naturally\n"
        "- Tags must include 10-15 items (broad, specific, and long-tail)\n\n"
        "TITLE RULE GUARDRAILS:\n"
        "1. At least 1 title must include a number (e.g. '5 facts about college debt').\n"
        "2. At least 1 title must be a question (e.g. 'is college a scam?').\n"
        "3. You are strictly banned from using clickbait phrases like 'you won't believe' or 'YOU WON'T BELIEVE'."
    ),
    output_schema=SeoOutput,
    output_key="seo_output"
)

def validate_seo(seo_data: dict) -> list[str]:
    """Validates that the generated SEO metadata respects all title rules and length limits.

    Args:
        seo_data: The output dictionary from the SEOAgent.

    Returns:
        A list of string descriptions for any failed validation checks.
    """
    errors = []
    titles = seo_data.get("titles", [])
    
    if len(titles) != 3:
        errors.append(f"Expected exactly 3 titles, found {len(titles)}.")
        
    has_number = False
    has_question = False
    
    for t in titles:
        t_clean = t.strip()
        # 1. Under 60 characters
        if len(t_clean) >= 60:
            errors.append(f"Title is too long ({len(t_clean)} chars): '{t_clean}'")
            
        # 2. Digit/number check
        if any(char.isdigit() for char in t_clean):
            has_number = True
            
        # 3. Question check
        if "?" in t_clean:
            has_question = True
            
        # 4. Banned clickbait
        if "you won't believe" in t_clean.lower():
            errors.append(f"Title contains banned clickbait phrase 'YOU WON'T BELIEVE': '{t_clean}'")
            
    if not has_number:
        errors.append("At least 1 title must contain a number.")
    if not has_question:
        errors.append("At least 1 title must be a question.")
        
    return errors

async def run_seo(script_data: dict, topic: str, max_retries: int = 3) -> dict:
    """Invokes the SEOAgent to generate metadata and validates it using title rules.

    Args:
        script_data: The script details generated by the ScriptAgent.
        topic: The original content topic/idea.
        max_retries: Maximum number of correction loops if validation fails.

    Returns:
        A dictionary matching the SeoOutput schema.
    """
    session_service = InMemorySessionService()
    runner = Runner(
        agent=seo_agent,
        app_name="agents",
        session_service=session_service,
        auto_create_session=True
    )
    
    user_msg = f"Topic: {topic}\n\nScript Data:\n{script_data}"
    
    for attempt in range(max_retries):
        async for event in runner.run_async(
            user_id="default_user",
            session_id="seo_session",
            new_message=types.Content(parts=[types.Part(text=user_msg)])
        ):
            pass
            
        session = await session_service.get_session(
            app_name="agents",
            user_id="default_user",
            session_id="seo_session"
        )
        
        seo_data = session.state.get("seo_output")
        if not seo_data:
            break
            
        # Serialize to dict if it's a Pydantic object
        seo_dict = seo_data.model_dump() if hasattr(seo_data, "model_dump") else seo_data
        
        # Check guardrails
        errors = validate_seo(seo_dict)
        if not errors:
            return seo_dict
            
        # Compile corrective feedback message and retry
        user_msg = (
            f"Your previous output violated SEO guardrail rules:\n"
            + "\n".join(f"- {err}" for err in errors)
            + "\n\nPlease rewrite and output the corrected SEO package schema."
        )
        
    # Return last attempt or fallback
    session = await session_service.get_session(
        app_name="agents",
        user_id="default_user",
        session_id="seo_session"
    )
    last_data = session.state.get("seo_output")
    if last_data:
        return last_data.model_dump() if hasattr(last_data, "model_dump") else last_data
        
    return {
        "titles": [],
        "description": "Failed to compile SEO metadata.",
        "tags": [],
        "thumbnail_brief": "",
        "chapter_markers": []
    }
